services:

  api:
    build: .
    container_name: digital_hunter_api
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=3311
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=digital_hunter
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: digital_hunter
    ports:
      - "3311:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql

volumes:
  mysql_data:
